sudo: false
language: ruby
rvm:
  - 2.3.3
  # - 2.4.0

env:
  global:
    - BROWSER=chrome

addons:
  chrome: stable

bundler_args: --path=vendor/bundle --without heroku

cache: bundler

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - sh -c "psql -c 'create database ts_crm_test;' -U postgres; fi"
  - "RAILS_ENV=test bundle exec rake spec:preparedb"

# Run specs
script:
  - "RAILS_ENV=test bundle exec rake spec:models"
  - "RAILS_ENV=test bundle exec rake spec:mailers"
  - "RAILS_ENV=test bundle exec rake spec:controllers"
  - "RAILS_ENV=test bundle exec rake spec:helpers"
  - "RAILS_ENV=test bundle exec rake spec:lib"
  - "RAILS_ENV=test bundle exec rake spec:mailers"
  - "RAILS_ENV=test bundle exec rake spec:routing"
  - "RAILS_ENV=test bundle exec rake spec:views"
  - "RAILS_ENV=test bundle exec rake spec:features"
  - "RAILS_ENV=test bundle exec rubocop"
