default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("TS_CRM_DATABASE_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("TS_CRM_DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("TS_CRM_DATABASE_USER") { '' } %>
  password: <%= ENV.fetch("TS_CRM_DATABASE_PASSWORD") { '' } %>

development:
  <<: *default
  database: <%= ENV.fetch("TS_CRM_DATABASE_DB") { 'ts_crm_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch("TS_CRM_DATABASE_DB") { 'ts_crm_test' } %>

production:
  <<: *default
  database: <%= ENV['TS_CRM_DATABASE_DB'] %>
