default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ts_crm_development

test:
  <<: *default
  database: ts_crm_test

production:
  <<: *default
  database: ts_crm_production
  username: ts_crm
  password: <%= ENV['TS_CRM_DATABASE_PASSWORD'] %>
